export const COUNTRIES = [
    {
        "id": 0,
        "name": "Namibia",
        "capital": "Windhoek",
        "population": "2,210,000",
        "area": "825,615",
        "description": "Namibia is Africa’s least densely populated country with an average of just 3 inhabitants per square km. The country consists mainly of high plateau which is flanked by the Namib desert along the Western coastline and the Kalahari Desert to the East, rendering large swaths of the country unfavorable to human occupation. Whilst the urban population has more than doubled since 1990, the rate of urbanization has slowed down in the past decade compared to previous decades, mainly as a result of the limited demographic resources of Namibia’s sparsely populated hinterland. // The country is subdivided into 14 regions and 121 constituencies and counts 17 cities with a population above 10,000 – the biggest being the capital Windhoek with just under 360,000 inhabitants. Most of the other larger urban agglomerations such as Rundu, Walvis Bay, Oshakati and Swakopmund are situated on the country’s borders which magnifies the relative “emptiness” of the interior parts of the country. The overall urbanization rate stands at 40.3%. //Contrary to most African nations, there are few agglomerations below 20,000 inhabitants and 13 out of the 17 cities have populations between 20,000 and 40,000. Whilst the distance between urban agglomerations has gradually decreased as more cities emerge and existing cities grow, the average distance between cities remains high by African standards at 107 km.",
        "description2": "The country is subdivided into 14 regions and 121 constituencies and counts 17 cities with a population above 10,000 – the biggest being the capital Windhoek with just under 360,000 inhabitants. Most of the other larger urban agglomerations such as Rundu, Walvis Bay, Oshakati and Swakopmund are situated on the country’s borders which magnifies the relative “emptiness” of the interior parts of the country. The overall urbanization rate stands at 40.3%. //Contrary to most African nations, there are few agglomerations below 20,000 inhabitants and 13 out of the 17 cities have populations between 20,000 and 40,000. Whilst the distance between urban agglomerations has gradually decreased as more cities emerge and existing cities grow, the average distance between cities remains high by African standards at 107 km."
    },
    {
        "id": 1,
        "name": "Sudan",
        "capital": "Khartoum",
        "population": "38,435,000",
        "area": "1,866,235",
        "description": "Sudan is the third largest country in Africa after Algeria and DR Congo. The climate ranges from arid deserts in the northern two-thirds of the country to semi-arid in the south and some pockets of tropical savannah in the southern-most regions. The North-Western part of the country is largely uninhabited. <br/> In 1950, Sudan was the most urbanized country of East Africa. The urbanization rate remains high and has gone up from 30% in 1990 to just over 40% in 2010. Over the same period, the number of urban agglomerations has practically tripled from 78 to 222 agglomerations in 2010. The largest growth can be seen in the number of secondary cities with fewer than 100,000 inhabitants. Whilst there were only 69 such cities in 1990, there are expected to be 296 cities in this category by 2020. The politico-administrative framework has not kept pace with these changes: in 2008, only 96 cities with more than 10,000 inhabitants were formally classified as cities whereas the country counted more than 200 agglomerations of similar size. <br/> Urbanization in Sudan is also characterized by a relatively large urban primacy index of 9.3, resulting from the dominance of the capital Khartoum, which is almost 10 times as large as the second city Nyala, both in terms of population and built area. The region of Jazira, within which the capital is located, is largely arid except for the delta between the two Nile rivers that have historically provided opportunities for the development of sophisticated irrigation techniques and have thereby contributed to high population growth in an otherwise barren region. This area of 20,000 square km, representing only 1.1% of Sudan’s overall surface area, accounts for 44% of the total urban population of the country."
    },
    {
        "id": 2,
        "name": "Mali",
        "capital": "Bamako",
        "population": "17,819,000",
        "area": "1,242,248",
        "description": "Mali has a relatively low population density of 14 inhabitants per square km. The population is very unevenly distributed across the territory: two-thirds of the territory - comprising mainly the regions of Timbuktu, Gao and Kidal - account for only 778,000 inhabitants in 2015 (i.e. less than 1 inhabitant/km2), of which a large majority is concentrated in the regional capitals. 96% of the Malian population lives in the other third of the territory, corresponding to a population density of 47 inhabitants/km2. <br/> The urban primacy index of Mali has steadily grown and currently scores 10. The capital Bamako dominates the urban population distribution by accounting for almost half of all urban dwellers. It is 10 times as large as the second biggest city Sikasso, both in terms of inhabitants and surface area. However, the number of smaller urban agglomerations between 10,000 and 49,999 inhabitants has seen large growth in the past few decades. In 1990, there were only 18 urban agglomerations in this category, but the number grew to 66 in 2010. <br/> Mali has one of the highest urban growth rates on the African continent. Only 17.8% of the total population were living in urban agglomerations in 1990. In 2010, the urbanization rate stood at 30%. At the same time, the country has seen significant population growth (from 8.2 to 15.2 million) which has also translated into a larger urban population (from 1.5 to 4.6 million)."
    },
    {
        "id": 3,
        "name": "Malawi",
        "capital": "Lilongwe",
        "population": "16,310,000",
        "area": "94,276",
        "description": "Malawi has four official cities and 28 rural market towns. The country’s urbanization profile is unique in Africa as the country does not count one but two dominant cities, Lilongwe and Blantyre, which are of similar size. Indeed, Malawi has the lowest primacy index of any country in the world. At the same time, it has one of the highest population densities in Africa at 173 inhabitants/km2. <br />Besides Lilongwe and Blantyre, Malawi only counts two further cities with more than 200,000 inhabitants (Zomba and Mzuzu) and one urban agglomeration of more than 100,000 inhabitants (Mpama/Likoswe UA). Until 25 years ago, Malawi was largely rural with an urbanization rate of just 10% in 1990. Since then, urbanization has largely been driven by people setting up informal settlements, thereby driving urbanization outside of an official planning framework. Today, there are 73 urban agglomerations in the country (up from 13 in 1990), but more than half of these agglomerations are not officially recognized as urban areas. <br /> Malawi’s “improvised” agglomerations present a significant challenge for managed urbanization. Unlike many other African nations, there is no real rural exodus. Instead urban agglomerations are built by the people themselves without the need to migrate towards cities per se. Policy-makers remain reluctant to provide more powers to the lowest administrative level, the Traditional Authorities, which often cover very large areas (on average 450 km2 with 67,000 inhabitants) without having the resources to provide adequate planning and development support."
    },
    {
        "id": 4,
        "name": "Kenya",
        "capital": "Nairobi",
        "population": "44,157,000",
        "area": "580,297",
        "description": "Kenya has one of the highest rates of urbanization in Sub-Saharan Africa at 64.7%. The definition of what counts as a city is largely political and recognizes only the core of the cities. However, in reality urban agglomerations not recognized as forming part of cities are integral to Kenya’s urban landscape. Five of these agglomerations have more than 1 million inhabitants and six have more than 400,000. <br /> These urban agglomerations often expand over a large territory and have relatively low population densities (on average 1235 inhabitants/km2) compared to agglomerations in other African countries. Most of the urban agglomerations can be found in Kenya’s highlands whereas littoral areas are more sparsely populated. Outside of Mombasa, there are very few if any urban agglomerations along the coastline. <br />Most of the urban population growth is happening in larger agglomerations above 200,000 inhabitants. Smaller cities and urban agglomerations are growing much slower. The largest agglomerations can be found in the Western highlands and north of Nairobi in the central part of the country. These two hold a combined population of more than 26 million and are likely to become two of the largest urban agglomerations in Africa in the years to come, extending over several hundreds of kilometers."
    }
];
